### ISSUE TITLE
Flutter 2.0 version compatability

### ISSUE THREAD

**Issue by karjaubayev** [fweinaug/expandable_text#13]
At least in my case with newer version of Flutter there is one bug in Localizations.dart file.

**Comment by Invincible1996** [comment]
I have the same issue

**Comment by Usmani7** [comment]
same issue

**Comment by Usmani7** [comment]
> At least in my case with newer version of Flutter there is one bug in Localizations.dart file.

same issue

**Comment by Invincible1996** [comment]
When will the issues be fixed, I want to upgrade my flutter version to 2.0.Hope to fix as soon as possible. Thanks.

**Comment by fweinaug** [comment]
I just released version 2.0. Please let me know if this version fixes your problems.
