### ISSUE TITLE
Expand on text tap

### ISSUE THREAD

**Issue by naamapps** [fweinaug/expandable_text#15]
It would be a nice addition if you add a bool `expandOnTextTap`, and when you tap on the text it will expand.
It's good when the text is plain text and you don't want to specifically tap the `... show more` text.

Maybe even add an option `shrinkOnTextTap` so it will be more complete, but it is not necessary for me really.

Thanks :)

**Comment by fweinaug** [comment]
Thanks! I just released version 2.1 which supports these two options. Let me know if everything works for you.

**Comment by naamapps** [comment]
Works great!
Thank you 👍
