### ISSUE TITLE
How can I use HtmlWidget  var in a expandable text ? 

### ISSUE THREAD

**Issue by davidsonmartins** [fweinaug/expandable_text#23]
I'm using an html text(coming from my database)  and the package flutter_widget_from_html to show the text in the app but the expandable_text only accept a String to limit the number if caracterers. 
How can I use HtmlWidget  var in a expandable text ? 

https://pub.dev/packages/flutter_widget_from_html

**Comment by fweinaug** [comment]
Unfortunately using widgets for the text is not possible, because of how the overflow calculation works.
