### ISSUE TITLE
Hashtags are not recognized directly after a new line

### ISSUE THREAD

**Issue by kevinschulze** [fweinaug/expandable_text#24]
Hello,
It looks like hashtags are not recognized directly after a line break. (see picture)
Maybe it's just a small adjustment of the regex expression?
I couldn't figure it out.

![grafik](https://user-images.githubusercontent.com/56517911/160254386-a1115530-1c17-413f-a665-3967cdef81b3.png)

**Comment by fweinaug** [comment]
thank you for creating the issue! I just released version 2.3 which should fix this problem.

**Comment by kevinschulze** [comment]
It works. Thanks for fixing the issue.
