### ISSUE TITLE
IsExpanded getter

### ISSUE THREAD

**Issue by Usmani7** [fweinaug/expandable_text#3]
First of all, thank you for this amazing plugin. 
Secondly, can we have a controller or getter or something which gives the current status of widget (isExpanded or not). We can use _expanded variable you used to get this.

**Comment by Usmani7** [comment]
in fact I have resolved this thing, if you allow me to share

**Comment by fweinaug** [comment]
Hi @Usmani7, I just published a new version (1.1) which includes this callback. Thank you for your contribution!
