### ISSUE TITLE
Support styling of 'expandText/collapseText'

### ISSUE THREAD

**Issue by Ariellaw** [fweinaug/expandable_text#5]
It is currently possible to change the color of the expandText/collapseText but not to change the style.

I am working on an app at the moment and one of the requirements is for the "see more"/"see less" to have a different style.
See screenshot

![image](https://user-images.githubusercontent.com/10836616/106015043-c16efe80-60c6-11eb-8074-b21c34564c77.png)

It would be great if that were possible with this package. :)

**Comment by fweinaug** [comment]
I just released version 1.3 which adds an option for the link style. Please let me know if it meets your requirements.

**Comment by Ariellaw** [comment]
Hey,

Thanks for making the change so quickly - it works wonderfully.
