### ISSUE TITLE
Add multiple textspans/styles within text

### ISSUE THREAD

**Issue by Ariellaw** [fweinaug/expandable_text#6]
At the moment it is currently only possible to pick one TextStyle for the entire text.  

It would be great if that could be changed.  

The requirements for the project that I am working on right now require that part of the text have a different style from the rest of the text.

It would be great if I were able to use this package to implement their design.

See screenshot.
![image](https://user-images.githubusercontent.com/10836616/106015560-45c18180-60c7-11eb-8a20-e22ed5ed81e9.png)

**Comment by fweinaug** [comment]
I just released version 1.3 which adds an optional prefix. Please let me know if it meets your requirements.

**Comment by Ariellaw** [comment]
The prefix works great, thank you!

There is one small issue though -
When I add a prefix, the *'see more*' is no longer positioned perfectly at
the end of the last line.
(with no prefix it's perfectly lined up).
Our designer is insistent that the '*see more*' be at the end of the last
line, she is very strict about these things. 😓

 I added a screenshot of the issue below:
[image: image.png]

**Comment by fweinaug** [comment]
This looks like a bug - I'll look into it.

**Comment by Ariellaw** [comment]
Thanks :)

**Comment by fweinaug** [comment]
I just released version 1.3.1 which hopefully should fix this problem. Please let me know if everything works for you.

**Comment by Ariellaw** [comment]
Thanks, it works great now.
