### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by rsnay** [fweinaug/expandable_text#7]
Thanks for the great package! It's been exactly what we need.

Has this package been migrated for null safety? When building an app with the `master` version of Flutter (to check for future compatibility issues with the app), the build fails with this error:
```
/[...]/flutter/master/x64/.pub-cache/hosted/pub.dartlang.org/expandable_text-1.2.0/lib/expandable_text.dart:117:56: Error: No named parameter with the name 'nullOk'.
        final locale = Localizations.localeOf(context, nullOk: true);
                                                       ^^^^^^
```

I'm not super familiar with what is needed for migration, but I could attempt a PR, if needed.
https://dart.dev/null-safety/migration-guide
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

**Comment by fweinaug** [comment]
I just published a first pre-release with null safety. Please let me know if everything works out for you.

**Comment by thumbeti** [comment]
Hi, 

I am also running into this issue after flutter upgrade.
/[....]/flutter/.pub-cache/hosted/pub.dartlang.org/expandable_text-1.3.2/lib/expandable_text.dart:153:56: Error: No named parameter with the name 'nullOk'.
        final locale = Localizations.localeOf(context, nullOk: true);

Could you please suggest on the fix.

**Comment by thumbeti** [comment]
I am also ran into this issue. and 2.0.0-nullsafety.0 worked for me.
Thanks a ton for that update.
When should I expect a release version of that changes.

**Comment by fweinaug** [comment]
> I am also ran into this issue. and 2.0.0-nullsafety.0 worked for me.
> Thanks a ton for that update.
> When should I expect a release version of that changes.

Thanks for letting me know! I'll release a new pre-release with the changes from version 1.3 soon. Final release as soon as null safety is stable.
